/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  canonicalUrl?: string;
  noIndex?: boolean;
  ogTitle?: string;
  ogDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href: string;
        openInNewTab?: boolean;
        rel?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      sourceUrl?: string;
      _type: "contentImage";
      _key: string;
    }
  | {
      caption?: string;
      rows?: Array<{
        cells?: Array<string>;
        _type: "tableRow";
        _key: string;
      }>;
      _type: "table";
      _key: string;
    }
  | {
      url: string;
      title?: string;
      _type: "embed";
      _key: string;
    }
  | {
      title: string;
      text?: string;
      label?: string;
      href?: string;
      _type: "cta";
      _key: string;
    }
  | {
      variant?: "default";
      _type: "horizontalRule";
      _key: string;
    }
>;

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
  wordpressId?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt?: string;
  body: BlockContent;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    sourceUrl?: string;
    _type: "image";
  };
  publishedAt: string;
  modifiedAt?: string;
  author?: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  readingTime?: number;
  featured?: boolean;
  seo?: Seo;
  wordpressId: number;
  legacyUrl?: string;
  sourceModifiedAt?: string;
  migrationWarnings?: Array<string>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: string;
  designation?: string;
  wordpressId?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | BlockContent
  | Category
  | Slug
  | AuthorReference
  | CategoryReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../orangeoffices/src/lib/sanity/queries.ts
// Variable: ALL_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc) {  _id, title, "slug": slug.current, excerpt, body, publishedAt, modifiedAt,  readingTime, featured,  featuredImage{alt, caption, asset->{_id, url, metadata{dimensions, lqip}}},  author->{_id, name, "slug": slug.current, designation, image{alt, asset->{url}}},  categories[]->{_id, title, "slug": slug.current},  seo{title, description, canonicalUrl, noIndex, ogTitle, ogDescription,    ogImage{alt, asset->{url}}},  wordpressId, legacyUrl}
export type ALL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  body: BlockContent;
  publishedAt: string;
  modifiedAt: string | null;
  readingTime: number | null;
  featured: boolean | null;
  featuredImage: {
    alt: string | null;
    caption: string | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
  author: {
    _id: string;
    name: string;
    slug: string;
    designation: string | null;
    image: {
      alt: string | null;
      asset: {
        url: string;
      } | null;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    canonicalUrl: string | null;
    noIndex: boolean | null;
    ogTitle: string | null;
    ogDescription: string | null;
    ogImage: {
      alt: string | null;
      asset: {
        url: string;
      } | null;
    } | null;
  } | null;
  wordpressId: number;
  legacyUrl: string | null;
}>;

// Source: ../orangeoffices/src/lib/sanity/queries.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {  _id, title, "slug": slug.current, excerpt, body, publishedAt, modifiedAt,  readingTime, featured,  featuredImage{alt, caption, asset->{_id, url, metadata{dimensions, lqip}}},  author->{_id, name, "slug": slug.current, designation, image{alt, asset->{url}}},  categories[]->{_id, title, "slug": slug.current},  seo{title, description, canonicalUrl, noIndex, ogTitle, ogDescription,    ogImage{alt, asset->{url}}},  wordpressId, legacyUrl}
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  body: BlockContent;
  publishedAt: string;
  modifiedAt: string | null;
  readingTime: number | null;
  featured: boolean | null;
  featuredImage: {
    alt: string | null;
    caption: string | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
  author: {
    _id: string;
    name: string;
    slug: string;
    designation: string | null;
    image: {
      alt: string | null;
      asset: {
        url: string;
      } | null;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    canonicalUrl: string | null;
    noIndex: boolean | null;
    ogTitle: string | null;
    ogDescription: string | null;
    ogImage: {
      alt: string | null;
      asset: {
        url: string;
      } | null;
    } | null;
  } | null;
  wordpressId: number;
  legacyUrl: string | null;
} | null;

// Source: ../orangeoffices/src/lib/sanity/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{"slug": slug.current}
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../orangeoffices/src/lib/sanity/queries.ts
// Variable: FEATURED_POSTS_QUERY
// Query: *[_type == "post" && featured == true && defined(slug.current)] | order(publishedAt desc)[0...6] {  _id, title, "slug": slug.current, excerpt, body, publishedAt, modifiedAt,  readingTime, featured,  featuredImage{alt, caption, asset->{_id, url, metadata{dimensions, lqip}}},  author->{_id, name, "slug": slug.current, designation, image{alt, asset->{url}}},  categories[]->{_id, title, "slug": slug.current},  seo{title, description, canonicalUrl, noIndex, ogTitle, ogDescription,    ogImage{alt, asset->{url}}},  wordpressId, legacyUrl}
export type FEATURED_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  body: BlockContent;
  publishedAt: string;
  modifiedAt: string | null;
  readingTime: number | null;
  featured: true;
  featuredImage: {
    alt: string | null;
    caption: string | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
  author: {
    _id: string;
    name: string;
    slug: string;
    designation: string | null;
    image: {
      alt: string | null;
      asset: {
        url: string;
      } | null;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    canonicalUrl: string | null;
    noIndex: boolean | null;
    ogTitle: string | null;
    ogDescription: string | null;
    ogImage: {
      alt: string | null;
      asset: {
        url: string;
      } | null;
    } | null;
  } | null;
  wordpressId: number;
  legacyUrl: string | null;
}>;

// Source: ../orangeoffices/src/lib/sanity/queries.ts
// Variable: POSTS_BY_CATEGORY_QUERY
// Query: *[_type == "post" && $category in categories[]->slug.current && defined(slug.current)] | order(publishedAt desc) {  _id, title, "slug": slug.current, excerpt, body, publishedAt, modifiedAt,  readingTime, featured,  featuredImage{alt, caption, asset->{_id, url, metadata{dimensions, lqip}}},  author->{_id, name, "slug": slug.current, designation, image{alt, asset->{url}}},  categories[]->{_id, title, "slug": slug.current},  seo{title, description, canonicalUrl, noIndex, ogTitle, ogDescription,    ogImage{alt, asset->{url}}},  wordpressId, legacyUrl}
export type POSTS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  body: BlockContent;
  publishedAt: string;
  modifiedAt: string | null;
  readingTime: number | null;
  featured: boolean | null;
  featuredImage: {
    alt: string | null;
    caption: string | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
  author: {
    _id: string;
    name: string;
    slug: string;
    designation: string | null;
    image: {
      alt: string | null;
      asset: {
        url: string;
      } | null;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    canonicalUrl: string | null;
    noIndex: boolean | null;
    ogTitle: string | null;
    ogDescription: string | null;
    ogImage: {
      alt: string | null;
      asset: {
        url: string;
      } | null;
    } | null;
  } | null;
  wordpressId: number;
  legacyUrl: string | null;
}>;

// Source: ../orangeoffices/src/lib/sanity/queries.ts
// Variable: RELATED_POSTS_QUERY
// Query: *[_type == "post" && _id != $id && count((categories[]._ref)[@ in $categoryRefs]) > 0 && defined(slug.current)] | order(publishedAt desc)[0...3] {  _id, title, "slug": slug.current, excerpt, body, publishedAt, modifiedAt,  readingTime, featured,  featuredImage{alt, caption, asset->{_id, url, metadata{dimensions, lqip}}},  author->{_id, name, "slug": slug.current, designation, image{alt, asset->{url}}},  categories[]->{_id, title, "slug": slug.current},  seo{title, description, canonicalUrl, noIndex, ogTitle, ogDescription,    ogImage{alt, asset->{url}}},  wordpressId, legacyUrl}
export type RELATED_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  body: BlockContent;
  publishedAt: string;
  modifiedAt: string | null;
  readingTime: number | null;
  featured: boolean | null;
  featuredImage: {
    alt: string | null;
    caption: string | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
  author: {
    _id: string;
    name: string;
    slug: string;
    designation: string | null;
    image: {
      alt: string | null;
      asset: {
        url: string;
      } | null;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    canonicalUrl: string | null;
    noIndex: boolean | null;
    ogTitle: string | null;
    ogDescription: string | null;
    ogImage: {
      alt: string | null;
      asset: {
        url: string;
      } | null;
    } | null;
  } | null;
  wordpressId: number;
  legacyUrl: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "post" && defined(slug.current)] | order(publishedAt desc) {\n  _id, title, "slug": slug.current, excerpt, body, publishedAt, modifiedAt,\n  readingTime, featured,\n  featuredImage{alt, caption, asset->{_id, url, metadata{dimensions, lqip}}},\n  author->{_id, name, "slug": slug.current, designation, image{alt, asset->{url}}},\n  categories[]->{_id, title, "slug": slug.current},\n  seo{title, description, canonicalUrl, noIndex, ogTitle, ogDescription,\n    ogImage{alt, asset->{url}}},\n  wordpressId, legacyUrl\n}': ALL_POSTS_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0] {\n  _id, title, "slug": slug.current, excerpt, body, publishedAt, modifiedAt,\n  readingTime, featured,\n  featuredImage{alt, caption, asset->{_id, url, metadata{dimensions, lqip}}},\n  author->{_id, name, "slug": slug.current, designation, image{alt, asset->{url}}},\n  categories[]->{_id, title, "slug": slug.current},\n  seo{title, description, canonicalUrl, noIndex, ogTitle, ogDescription,\n    ogImage{alt, asset->{url}}},\n  wordpressId, legacyUrl\n}': POST_BY_SLUG_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)]{"slug": slug.current}': POST_SLUGS_QUERY_RESULT;
    '*[_type == "post" && featured == true && defined(slug.current)] | order(publishedAt desc)[0...6] {\n  _id, title, "slug": slug.current, excerpt, body, publishedAt, modifiedAt,\n  readingTime, featured,\n  featuredImage{alt, caption, asset->{_id, url, metadata{dimensions, lqip}}},\n  author->{_id, name, "slug": slug.current, designation, image{alt, asset->{url}}},\n  categories[]->{_id, title, "slug": slug.current},\n  seo{title, description, canonicalUrl, noIndex, ogTitle, ogDescription,\n    ogImage{alt, asset->{url}}},\n  wordpressId, legacyUrl\n}': FEATURED_POSTS_QUERY_RESULT;
    '*[_type == "post" && $category in categories[]->slug.current && defined(slug.current)] | order(publishedAt desc) {\n  _id, title, "slug": slug.current, excerpt, body, publishedAt, modifiedAt,\n  readingTime, featured,\n  featuredImage{alt, caption, asset->{_id, url, metadata{dimensions, lqip}}},\n  author->{_id, name, "slug": slug.current, designation, image{alt, asset->{url}}},\n  categories[]->{_id, title, "slug": slug.current},\n  seo{title, description, canonicalUrl, noIndex, ogTitle, ogDescription,\n    ogImage{alt, asset->{url}}},\n  wordpressId, legacyUrl\n}': POSTS_BY_CATEGORY_QUERY_RESULT;
    '*[_type == "post" && _id != $id && count((categories[]._ref)[@ in $categoryRefs]) > 0 && defined(slug.current)] | order(publishedAt desc)[0...3] {\n  _id, title, "slug": slug.current, excerpt, body, publishedAt, modifiedAt,\n  readingTime, featured,\n  featuredImage{alt, caption, asset->{_id, url, metadata{dimensions, lqip}}},\n  author->{_id, name, "slug": slug.current, designation, image{alt, asset->{url}}},\n  categories[]->{_id, title, "slug": slug.current},\n  seo{title, description, canonicalUrl, noIndex, ogTitle, ogDescription,\n    ogImage{alt, asset->{url}}},\n  wordpressId, legacyUrl\n}': RELATED_POSTS_QUERY_RESULT;
  }
}
